# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS_Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Speculid', :path => '../'

end

target 'iOS_Example.watchOS_Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Speculid', :path => '../'

end

target 'iOS_Example.watchOS_Example.watchOS_Example_Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Speculid', :path => '../'

end

target 'macOS_Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Speculid', :path => '../'

end

target 'tvOS_Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Speculid', :path => '../'

end
