url: "https://speculid.com"
logo_url: /images/Logo.svg
theme: jekyll-theme-cayman
show_downloads: false
google_analytics: UA-33667276-14
show_signup: true
plugins:
  - jekyll-sitemap
exclude:
  - applications
  - bin
  - CairoSVG*
  - certs
  - examples
  - frameworks
  - scripts
  - Speculid*
  - tests
  - "*.plist"
  - Gemfile*
  - Podfile*
  - Pods
  - "*.orig.*"
  - "*.toc.*"
