logo_url: /images/Logo.svg
theme: jekyll-theme-cayman
show_downloads: false
google_analytics: UA-33667276-14
show_signup: true
plugins:
  - jekyll-sitemap
exclude:
  - "*"
include:
  - "index.md"
  - "images"
  - "*.png"
  - "*.svg"
  - "*.ico"
  - "browserconfig.*"
  - "*.webmanifest"
  - "assets/js/signup-form.js"
