/* Generated by autorevision - do not hand-hack! */

let VCS_TYPE			= "git"
let VCS_BASENAME		= "speculid"
let VCS_UUID:	String?	= "b6fd659a7d2088d5420f962a307b1f7f7e5d0604"
let VCS_NUM:	Int		= 507
let VCS_DATE			= "2017-10-01T16:35:08Z"
let VCS_BRANCH:	String	= "feature/remove-inkscape-imagick"
let VCS_TAG:	String?	= "1.0.2"
let VCS_TICK:	Int?	= 38
let VCS_EXTRA:	String?	= "20"

let VCS_ACTION_STAMP:	String?	= "2017-10-01T16:35:08Z!leogdion@brightdigit.com"
let VCS_FULL_HASH:		String	= "1153816014037627d858233f19dfa4313b73379a"
let VCS_SHORT_HASH:		String	= "1153816"

let VCS_WC_MODIFIED:	Bool	= true

/* end */
