/* Generated by autorevision - do not hand-hack! */

let VCS_TYPE			= "git"
let VCS_BASENAME		= "speculid"
let VCS_UUID:	String?	= "b6fd659a7d2088d5420f962a307b1f7f7e5d0604"
let VCS_NUM:	Int		= 406
let VCS_DATE			= "2016-10-15T17:09:52Z"
let VCS_BRANCH:	String	= "feature/desktop-analytics"
let VCS_TAG:	String?	= "1.0.0-beta1"
let VCS_TICK:	Int?	= 14
let VCS_EXTRA:	String?	= "7"

let VCS_ACTION_STAMP:	String?	= "2016-10-15T17:09:52Z!leogdion@brightdigit.com"
let VCS_FULL_HASH:		String	= "8b61b51024fdacca0d199ad9676ff82c12b8bda1"
let VCS_SHORT_HASH:		String	= "8b61b51"

let VCS_WC_MODIFIED:	Bool	= true

/* end */
