# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)

platform :mac do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "Speculid.xcodeproj")
    build_mac_app(scheme: "Speculid")
    upload_to_app_store(skip_metadata: true, skip_screenshots: true, run_precheck_before_submit: false)
  end
end
